Event Handler
brunorodmoreira/ollie-observability pull request #8
Opened 2023-12-08 18:29 UTC by v-hansen

2023-12-12 14:20 UTC, brunorodmoreira requested changes

2023-12-12 14:20 UTC, brunorodmoreira commented on packages/vtex-io-logger/src/api/with-full-logger.ts
> +    events: events ?? config.events ?? {},
The function `injectEnhancedLoggerToRoutes` already has a similar validation to check if the routes exists and if not it returns directly without any mutation, so I think it's kind of redundant. What do you think? We can remove the validation from the inject function if you want.

2023-12-12 14:20 UTC, brunorodmoreira commented on packages/vtex-io-logger/src/core/instrumentation/events/full-logging-middleware-factory.ts
> +}
Well, it's almost the same for routes. Maybe we can think about a refactor to avoid repetition after.

2023-12-12 14:20 UTC, brunorodmoreira commented on packages/vtex-io-logger/src/core/instrumentation/events/instrument-events.ts
> +}
Same as before.

2023-12-14 16:56 UTC, v-hansen commented on packages/vtex-io-logger/src/api/with-full-logger.ts
> +    events: events ?? config.events ?? {},
makes sense

2024-02-26 17:06 UTC, brunorodmoreira approved these changes

2024-02-26 17:07 UTC, merged